---
  - hosts: [master]
    gather_facts: no
    become: yes
    become_user: root
    become_method: sudo
    tasks:
    - name: Create registry authorization secret
      shell: kubectl create secret generic {{ secret_name }} --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson