---
  - hosts: [master]
    gather_facts: no
    tasks:
    - name: Create registry authorization secret
      shell: kubectl create secret generic {{ secret_name }} --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson