- name: Disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Set SELinux permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Force iptables routing
  copy:
    src: scripts/k8s.conf
    dest: /etc/sysctl.d

- name: Reload sysctl
  shell: sysctl --system

- name: Ensure br_netfilter is loaded
  modprobe:
    name: br_netfilter
    state: present
  