apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ vdcId }}"
  labels:
    vdc: "{{ vdcId }}"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "{{ master_ip }}"
    path: "/mnt/data/{{ vdcId }}"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ vdcId }}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      vdc: "{{ vdcId }}"
