apiVersion: v1
kind: Service
metadata:
  name: ds4m
spec:
  type: NodePort
  selector:
    component: ds4m
  ports:
  - name: http
    port: 8080
    targetPort: 50003

---
apiVersion: v1
kind: Pod
metadata:
  name: ds4m
  labels:
    component: ds4m
spec:
  containers:
  - name: ds4m
    image: ditas/decision-system-for-data-and-computation-movement
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint
  volumes:
  - name: blueprint
    hostPath:
      path: /home/cloudsigma/blueprint
      type: Directory