---
  apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    name: glusterfs-storage-single
  provisioner: kubernetes.io/glusterfs
  parameters:
    resturl: "{{ heketi_url.stdout }}"
    volumetype: none