---
  - hosts: [all]
    gather_facts: no
    become: yes
    become_user: root
    become_method: sudo
    strategy: free
    tasks:
    - name: Ensures certificate folder exists exists
      file: 
        path: "/etc/docker/certs.d/{{ repo_name }}" 
        state: directory
      when: cert_file is defined
      
    - name: Copy repository certificate to host
      copy: 
        src: "{{ cert_file }}"
        dest: "/etc/docker/certs.d/{{ repo_name }}/ca.crt"
      when: cert_file is defined
    - name: reset ssh connection to force it to log in again
      meta: reset_connection
    - name: Log in to docker
      become: no
      shell: docker login --username {{ repo_username }} --password {{ repo_password }} {{ repo_name }}
    