---
  - hosts: [master]
    become: yes
    gather_facts: no
    tasks:
      - name: using kubernetes init and gathering output info
        shell: kubeadm init --pod-network-cidr=10.244.0.0/16

      - name: Ensure .kube directory exists.
        file:
          path: ~/.kube
          state: directory

      - name: Symlink the kubectl admin.conf to ~/.kube/conf.
        file:
          src: /etc/kubernetes/admin.conf
          dest: ~/.kube/config
          state: link

      - name: Add Flannel network
        shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml

      - name: taint cluster to allow pod deployments on master
        shell: kubectl taint nodes --all node-role.kubernetes.io/master-
      
      - name: Creating token for slaves to join
        shell: kubeadm token create --print-join-command
        register: kube_join

      - name: Setting variable to join other nodes
        set_fact: join_command="{{ kube_join.stdout }}"

      - name: Getting slaves join command
        debug: msg={{ kube_join.stdout }}
        when: "'kubeadm join' in kube_join.stdout"
      
  - hosts: [slave]
    become: yes
    gather_facts: no
    strategy: free
    tasks:
      - name: joining nodes to cluster
        command: "{{ hostvars[groups['master'][0]]['join_command'] }}"
