- hosts: all
  become: yes
  tasks:
  - include_tasks: prepare-RedHat.yml
    when: ansible_os_family == 'RedHat'

- hosts: all
  become: yes
  tasks:
  - name: Ensure br_netfilter is loaded
    modprobe:
      name: br_netfilter
      state: present

- hosts: all
  become: yes

  vars:
    kubernetes_allow_pods_on_master: True
    kubernetes_apt_ignore_key_error: true

  roles:
    - geerlingguy.kubernetes